
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANA
 */
public class Datos extends javax.swing.JFrame {

    /**
     * Creates new form Datos
     */
    public Datos() {
        initComponents();
        
        ArrayList<Texto> texto = new ArrayList<>();
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

       
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtleer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btntraduc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtleer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtleerActionPerformed(evt);
            }
        });

        jLabel1.setText("    Traductor Español-Braille");

        jLabel2.setText("Escribe una oracion");

        btntraduc.setText("Traducir");
        btntraduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntraducActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtleer, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btntraduc)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtleer, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btntraduc)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtleerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtleerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtleerActionPerformed

    private void btntraducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntraducActionPerformed
        String Traduccion=txtleer.getText();
        if(Traduccion.equals(null) || Traduccion.equals("")){
           JOptionPane.showMessageDialog(null,"Ingrese alguna oracion!!!!");
            return;
        }
        Traduccion=Traduccion.toLowerCase();
        Traduccion=Traduccion.replaceAll("\n", " ");
        char caracter[]=new char[10000];
                caracter= Traduccion.toCharArray();
        Texto t=new Texto(caracter);
        String[] imagenes =new String[10000];
                imagenes= t.getPaltraduc();
        
        abrir(pagina(imagenes));
        JOptionPane.showMessageDialog(null,"Listo");
        try {
            Runtime.getRuntime().exec("cmd /c start Visualizar.html");
        } catch (Exception e) {
        }   String txtTraduccion=txtleer.getText();
        if(txtTraduccion.equals(null) || txtTraduccion.equals(" ")){
           JOptionPane.showMessageDialog(null,"Ingrese alguna oracion");
            return;
        }
       
        abrir(pagina(imagenes));
        JOptionPane.showMessageDialog(null,"Listo");
        try {
            Runtime.getRuntime().exec("cmd /c start Visualizar.html");
        } catch (Exception e) {
        }        // TODO add your
        
    }//GEN-LAST:event_btntraducActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntraduc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtleer;
    // End of variables declaration//GEN-END:variables

public static void abrir(String ar){
        File ok =new File(".");
        FileWriter fichero = null;
        PrintWriter pw = null;
        try {
            fichero = new FileWriter("Visualizar.html", false);
            fichero.write(ar);
            
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                //Nuevamente aprobechamos el finally para
                //asegurarnos que se cierra el fichero
                if (null != fichero) {
                    fichero.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
    }

    static String linea;
    static String archivoAt="";
    public static String leer() {
        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;
        File ok =new File(".");
        String lin = "";
        try {
       
            archivo = new File(ok.getCanonicalPath()+"\\Visualizar.html");
            archivoAt=""+ok.getCanonicalPath()+"\\Visualizar.html";
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);
          
                lin = linea;
//            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
   
            try {
                if (null != fr) {
                    fr.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
        return lin;
    }
    public String pagina(String[] imagenes){
            String txtHtml="";
            txtHtml += "<!DOCTYPE HTML>";
            txtHtml += "<html>";
            txtHtml += "	<head>";
            txtHtml += "	<meta charset=utf-8>";
            txtHtml += "	</head>";
            txtHtml += "	<body>";
            txtHtml += "";
            txtHtml += "		<!-- Nav -->";
            txtHtml += "			<nav id=\"nav\">";
            txtHtml += "				<ul class=\"container\">";
            txtHtml += "					<li><a href=\"#contact\">Traductor Español-Braille</a></li>";
            txtHtml += "				</ul>";
            txtHtml += "			</nav>";
            txtHtml += "				";
            txtHtml += "		<!-- Contact -->";
            txtHtml += "			<div class=\"wrapper style4\">";
            txtHtml += "				<article id=\"contact\" class=\"container 75%\">";
            for (int i=0;i<imagenes.length;i++) {
                if(imagenes[i]!=null && imagenes[i]!="")
                txtHtml+="<img src=\"src\\imagenes\\"+imagenes[i]+"\" width=90 height=90>";
            }
            txtHtml += "				</article>";
            txtHtml += "			</div>";
            txtHtml += "";
            txtHtml += "	</body>";
            txtHtml += "</html>";

        return txtHtml;
    }
}



